### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by whoiskevinrich** [awsdocs/aws-toolkit-visual-studio-user-guide#6] opened 2019-07-15 21:02 UTC
The documentation available at:

 https://github.com/awsdocs/aws-toolkit-visual-studio-user-guide/blob/master/doc_source/deployment-beanstalk-custom-netcore.md

is out of date. project.json hasn't existed since dotnet 1.0 which is over a year old.

**Comment by ghost** [comment] 2019-08-15 15:42
Thanks for raising this issue. A member of the team will begin taking action and will provide updates here as they make progress.

Paul
AWS Documentation

**Comment by Doug-AWS** [comment] 2019-09-26 16:35
We need to wade through the "Deploying to Elastic Beanstalk" section, https://docs.aws.amazon.com/en_us/toolkit-for-visual-studio/latest/user-guide/deployment-beanstalk.html, and fix any errors. Unfortunately this doc set is in maintenance mode, so we are unable to take on this task at this time.

**Comment by Doug-AWS** [comment] 2019-09-26 16:37
Here is another comment about that section, specifically "Deploying an ASP.NET Core Application to Elastic Beanstalk", http://docs.aws.amazon.com/en_us/toolkit-for-visual-studio/latest/user-guide/deployment-beanstalk-netcore.html:

I am trying to deploy a .NET Core Web API to Elastic Beanstalk.

Everything here assumes that things are going well during the deployment, but if there are issues that arise, finding the relevant information to resolve the problem is incredibly difficult (for this I still haven't found the answer).

I initially ran into an issue where the CNAME was not available, even after I typed numerous things that should have almost certainly been available. I had to search forums to find someone saying that their IAM account not belonging to a particular group was the issue. Not a helpful error message given the issue.

Now I am running into an issue on the next page where the drop down box for container type is not populating at all, and it is a mandatory field. This document says to leave the defaults but unfortunately for me, that is not possible.

I am now writing my own documentation with error handling steps because so far, this content does not seem to exist in the necessary detail.

**Comment by whoiskevinrich** [comment] 2019-09-26 17:47
> We need to wade through the "Deploying to Elastic Beanstalk" section, https://docs.aws.amazon.com/en_us/toolkit-for-visual-studio/latest/user-guide/deployment-beanstalk.html, and fix any errors. Unfortunately this doc set is in maintenance mode, so we are unable to take on this task at this time.

How can AWS state they "provide all the familiar tooling and integrations .NET developers expect" but have documentation in Maintenance mode?

The .NET language is in continual development. .NET developers _expect_ continuously updated documentation as found with the language documentation.

It seems to me that either you would either support the language or you would not. I understand the maintainers of this git repo are accountable to others, but this AWS stance is baffling.

![image](https://user-images.githubusercontent.com/2496620/65711750-72383a00-e04a-11e9-91a4-d0843d46cbbe.png)

**Comment by Doug-AWS** [comment] 2019-09-26 17:57
I understand and empathize with your comments. All I can say is that we are working hard at adding more head count to cover our existing workload.

**Comment by Doug-AWS** [comment] 2019-09-27 13:57
I'm updating the section using Visual Studio 2019.

**Comment by joshbean** [comment] 2023-06-15 19:18
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).

**Closed as completed by joshbean** 2023-06-15 19:18 UTC
Labels: archived
